#pragma once

float TIME_BACKGROUND   = 0.05f;
int HEIGHT_WINDOW       = 1000;
int WIDTH_IMAGE_PIX     = 1280;
int HEIGHT_IMAGE_PIX    = 721;
int WIDTH_IMAGE_FRAME   = 12;
int HEIGHT_IMAGE_FRAME  = 21;
int EMPTY_WIDTH_FRAME   = 8;
int EMPTY_HEIGTH_FRAME  = 1;

